print ('Glo Academy')
print ('Glo', end=' ')
print ('Academy')
print ('Glo', 'Academy')
print ('Glo','Academy', sep='HELLo')
print ('G', 'l', 'o', sep='', end=' ')
print ('A','c', 'a','d','e','m','y', sep='')
print ('Glo', end='###')
print ('Academy')
print('G','l','o','A','c','a','d','e','m','y', sep='"GloAcademy"')