r = int(input())
k = int(input())
n = int(input())
num = (r * 100)
num2 = ((num + k) * n)
num3 = (num2 // 100)
num4 = (num2 % 100)
#print (num)
#print (num2)
#print (num3)
#print (num4)
print ('За', n, 'мяча нужно заплатить', num3, 'рублей и', num4, 'копеек')
