r = int(input())
k = int(input())
n = int(input())
num = (k / 100)
num2 = ((r + num) * n)
num3 = (num2 // 1)
num4 = (num2 % 1)
num5 = round(num4, 1)
print('За', n, 'мяча нужно заплатить', num3, 'рублей и', num5, 'копеек')