num = int(input())
a = (num % 10)
b = ((num % 100) // 10)
c = ((num % 1000) // 100)
abount = (a + b + c)
#print (a)
#print (b)
#print (c)
print('У числа', num, 'сумма последних трех цифр равна', abount)